version: '3.8'
services:
  app:
    image: daimonix/modulith-booking-service
    container_name: spring_app
    ports:
      - "8080:8080"
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - redis
      - analytics

  analytics:
    image: daimonix/modulith-booking-analytics
    container_name: analytics
    ports:
      - "8081:8081"

  redis:
    image: "redis:7"
    container_name: redis
    ports:
      - "6379:6379"
