version: '3.8'
services:
  app:
    image: daimonix/modulith-booking-service
    container_name: spring_app
    ports:
      - "8080:8080"
    environment:
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

  redis:
    image: "redis:7"
    container_name: redis
    ports:
      - "6379:6379"