{
 "title": "Total Analytics Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "jvm_memory_committed_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 8 },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "New Users Today",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 8 },
   "targets": [
    { "expr": "analytics_new_users_today", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Analytics Total Events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 15 },
   "targets": [
    { "expr": "analytics_events_total", "legendFormat": "__auto" }
   ]
  }
 ]
}