apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      name: app
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: daimonix/modulith-booking-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: booking-configmap
                  key: redis-host
            - name: SPRING_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: booking-configmap
                  key: redis-port
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
